name = input("Enter name: ")
marks = int(input("Enter marks: "))
phone = input("Enter phone number: ")
a = "The name of the student is {}, his marks is {} and phone number is {}".format(name, marks, phone)
print(a)